services:
  - type: web
    name: link-shortener
    env: php
    plan: free
    region: oregon
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:nNMd3QwQyUxLXrNXPA1G8XTIvD2sILaw0t67l3EAje4=
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://link-shortener.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
            type: pserv
            name: link-shortener-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: link_shortener
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: null
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel
      - key: VITE_APP_NAME
        value: Laravel

databases:
  - name: link-shortener-db
    databaseName: link_shortener
    user: root
    plan: free
    region: oregon
